### ISSUE TITLE
Write to Hugging Face hub component

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#113]

**Comment by PhilippeMoussalli** [comment]
https://github.com/huggingface/datasets/issues/3753
https://github.com/huggingface/datasets/issues/5665
https://github.com/huggingface/datasets/issues/3444
https://towardsdatascience.com/my-experience-with-uploading-a-dataset-on-huggingfaces-dataset-hub-803051942c2d

**Comment by PhilippeMoussalli** [comment]
Submitted issue: 
https://github.com/huggingface/huggingface_hub/issues/1475
