### ISSUE TITLE
Map subset names between components

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#180]
### Problem Statement

To make the pre-made components more useable we need a good way to specify your own columns without having to change the component specs, component code and rebuild the Docker image.

This applies for all component types:
* `LoadComponent`: user might want to change the default column names of the source dataset 
* `WriteComponent`: user might want to rename final written dataset differently then `subset_field`
* `TransformComponent`: user may want to introduce their own map component that produces columns of certain field names but then want to use a resuable component with different field/subset names. In that case, they will need to remap the column names. 

 
### Proposed Approach

[Bert]: I would suggest having support for passing a `renaming dictionary` which contains a mapping of the columns in the spec and the columns that you want to use instead.

Suppose that the `fondant_spec` contains these columns
```yaml
consumes:
  images:
    fields:
      data:
        type: binary

produces:
  images:
    fields:
      data:
        type: binary
      width:
        type: int16
      height:
        type: int16
```

but you want `pictures_content` and `pictures_w`, `pictures_h` because your previous component produces this.

```python

column_mapping = {
                                  'images_data': 'pictures_content',
                                  'images_width': 'pictures_w',
                                  'images_height': 'pictures_h'
                                  }

caption_images_op = ComponentOp.from_registry(
    name="<DOCKER_IMAGE>",
    arguments={},
    number_of_gpus=1,
    node_pool_name="model-inference-pool",
    column_mapping=column_mapping
)
```

While reading/writing the parquet file, Fondant can use this mapping to retrieve/write the correct subsets.

[Philippe]: this might work but can introduce a lot of complexity -> we might want to introduce a taxonomy.

There are advantages or disadvantages to both. I created a schema to make this a bit more clear -> [to Taxonomy or not to Taxonomy?](https://excalidraw.com/#room=8b0695dbe8fb8594a53b,EXnYA0oCzOABBOYyZY2oNQ)

**Taxonomy free approach:** 

* Assumes the users know the one-to-one mapping between fields/subsets produced/consumed by custom components and their equivalent in the reusable components (and vice-versa) 

* Fields under subsets may switch between components -> undesired behavior may occur 

 * User needs to track how fields/subset names are changed throughout the pipeline and  take extra consideration when defining the renaming dictionary (additional work at the user's end)

**Taxonomy approach:** 

* Less complexity since users have to conform to a taxonomy -> no need to track how subsets/fields are changing between components -> less unpredictable behavior  

* Not very flexible for custom fields -> may be circumvented by users defining custom fields in a special subset or calculating that field and operating on it in the same component (e.g. comment_to_code_ratio) 

* Users only need to define renaming dictionary for write and sink component (optional for sink)

* Easier for development -> less unpredictable behavior 

[Meeting 05/07]:
* Conclusion was to go for a taxonomy free approach since taxonomies are quite restrictive. 
* Stick with only mapping the inputs for now, outputs will be written based on the name defined in the component schema
* Renaming is only done within a component and does not change the name of the columns unless specified in the output subsets (except for the load and sink component)

**Illustration of implementation** 

  * **LoadComponent**

     * Load components should update the manifest based on the mapping dictionary since we want to transform the original dataset to a desired schema that should persist throughout the rest of the pipeline (e.g. `picture` field to `data` field under `images` subset)

<table>
<tr>
<th width="400px">Input dataset</th>
<th width="400px">Component spec</th>
<th width="400px">Mapping dictionary</th>
<th width="400px">Output manifest</th>
</tr>
<tr>
<td>

```json
[
  "picture",
  "breadth",
  "peak"
]
```

</td>
<td>

```yaml
consumes:

produces:
  images:
    fields:
      width:
        type: int32
     height:
        type: int32
    data:
        type: binary

```

</td>
<td>

```json
{
  "pictures":
     "images_data",
  "breadth":
     "images_width",
  "peak":
     "images_height"
}
```

</td>
<td>

```json
{
  "subsets": {
    "images": {
      "location": "...",
      "fields": {
        "width": {
          "type": "int32"
        },
        "height": {
          "type": "int32"
        },
        "data": {
          "type": "binary"
       }
     }
   }
 }
```

</td>
</tr>
</table>

  

  * **Transform Component**
     * Unlike load/Write components. The transform dictionary of a transformation components  is only used to temporarily change the name of the fields and does not change the final field names (unless specified in the output subsets of the specs). 
     * Transformations across subsets are not allowed and should be checked statically before  when compiling the pipeline          (e.g. `images_embedding` -> `vectors_embedding`)
 

<table>
<tr>
<th width="400px">Input manifest</th>
<th width="400px">Component spec</th>
<th width="400px">Mapping dictionary</th>
<th width="400px">Output manifest</th>
</tr>
<tr>
<td>

```json
{
  "subsets": {
    "images": {
      "location": "...",
      "fields": {
        "width": {
          "type": "int32"
        },
        "height": {
          "type": "int32"
        },
        "data": {
          "type": "binary"
        }
      }
    },
```

</td>
<td>

```yaml
consumes:
  images:
    fields:
      data:
        type: binary

produces:
  vectors:
    fields:
      data:
        type: binary

```

</td>
<td>

```json
{
  "images_data": 
      "pictures_data",
}
```

</td>
<td>
  

```json
{
  "subsets": {
    "images": {
      "location": "...",
      "fields": {
        "width": {
          "type": "int32"
        },
        "height": {
          "type": "int32"
        },
        "data": {
          "type": "binary"
       }
    "vectors": {
          "location": "...",
          "fields": {
            "data": {
              "type": "binary"
        }
     }
   }
 }
```

</td>
</tr>
</table>

  * **Sink/Write Component**  

<table>
<tr>
<th width="400px">Input manifest</th>
<th width="400px">Component spec</th>
<th width="400px">Mapping dictionary</th>
<th width="400px">Output dataset</th>
</tr>
<tr>
<td>

```json
{
  "subsets": {
    "images": {
      "location": "...",
      "fields": {
        "width": {
          "type": "int32"
        },
        "height": {
          "type": "int32"
        },
        "data": {
          "type": "binary"
        }
      }
    },
    "captions": {
      "location": "...",
      "fields": {
        "data": {
          "type": "binary"
        }
      }
    },
    "embeddings": {
      "location": "...",
      "fields": {
        "data": {
          "type": "binary"
        }
      }
    }
  }
}
```

</td>
<td>

```yaml
consumes:
  images:
    fields:
      data:
        type: binary
       width
         type: int32
        },
        height: {
          type: int32
        },
   vectors: {
       fields: {
          data: {
            type: binary
     
```

</td>
<td>

```json
{
  "images_data": 
      "image",
  "images_width": 
      "width",
  "images_height": 
      "height",
  "vectors_data": 
      "embedding",
}
```

</td>
<td>
  

```json
[
  "image",
  "width",
  "height",
  "embedding
]
```

</td>
</tr>
</table> 

### Implementation Steps/Tasks

* Add input mapping dictionary as an optional component to the components 
* Add specific implementation per component type
  Changes need to be made before transforming and writing components for all component types. Both `DaskDataLoader` and `DaskDataWriter` will now accept an optional argument `mapping_dictionary` to rename the columns of the dataframe before processing or writing. 

   * Load component 
      * Mapping dictionary is used to map the loaded dataframe before writing (`DaskDataWriter`)
      
   * Transform component 
      * Mapping dictionary is used to map the loaded dataframe before transforming (`DaskDataLoader`)
      * The inverse of the mapping dictionary is then used to revert the mapping of the dataframe before writing (`DaskDataWriter`) 
     
   * Sink components (out of scope since it's not implemented yet) See [here](https://github.com/orgs/ml6team/projects/1/views/1?pane=issue&itemId=28334529)   
      * Mapping dictionary is used to map the load dataframe before sinking (`DaskDataSink`)

 
### Testing

* Pass remapping dictionary and check that we're able to write/process the dataset with the specified fields ([location](https://github.com/ml6team/fondant/blob/main/tests/test_component.py)).  

* Check that descriptive errors are returned to the user when attempting to compile a pipeline with invalid remapping dictionary or when attempting to remap subsets ([location](https://github.com/ml6team/fondant/blob/main/tests/test_pipeline.py)).

### Documentation

Update [custom_component.md](https://github.com/ml6team/fondant/blob/main/docs/custom_component.md) with required info.

### Dependent features

[WriteComponent](https://github.com/orgs/ml6team/projects/1/views/1?pane=issue&itemId=28334529). Not hard dependency but preferrably implemented in order to properly validate.  

### Additional Notes

**Caveats:** 
* We're now defining one remapping dictionary and specifying what it should transform depending on the component type. 
(e.g. transform output for LoadComponent, transform input for TransformComponent, ...).

* The sink/write component is a bit of an odd-ball since in theory it's transforming the input subsets but it can be interpreted as transforming the output (if you consider the output to be the final sinked dataframe to a remote storage and not the final written dataset)

**Comment by RobbeSneyders** [comment]
Closing in favor of #689
