### ISSUE TITLE
Move to Pandas dataframes as interface

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#183]
### Problem Statement

Currently, the Fondant component interface is based on a Dask Dataframe:

```Python
import dask.dataframe as dd

from fondant.component import TransformComponent


class MyComponent(TransformComponent):

    def transform(dataframe: dd.Dataframe, **kwargs): -> dd.Dataframe
        # User code goes here
```

Which means that the user needs to work with a Dask Dataframe, which raises two challenges:
- Dask requires quite a big learning curve to use efficiently. 
- It's hard to let Fondant completely handle Dask optimization such as indexing and partitioning as this might interfere with user Dask code

### Proposed Approach

Instead, we can base our interface on a Pandas dataframe:

```Python
import pandas as pd

from fondant.component import TransformComponent


class MyComponent(TransformComponent):

    def transform(dataframe: pd.Dataframe, **kwargs): -> pd.Dataframe
        # User code goes here
```

Which lets the user write code handling an in-memory Pandas dataframe, and moves all Dask specific optimization to Fondant.

Since a Dask dataframe is composed of many smaller Pandas dataframes (partitions) split along the index, this implementation should align nicely with the internal Dask design. It should also scale to distributed computing since the unit of distribution is a partition.

The Fondant component class can leverage [`map_partitions`](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.map_partitions.html) in the `_process_dataset()` method to achieve this.

### Limitations

- The `map_partitions` method assumes that the index and divisions are unchanged, and otherwise requires resetting the divisions on the result, which can be expensive if they need to be recalculated.

  I propose to check if the returned index is identical to the original index. If it is, this assumption is valid. If it is not, we call `clear_divisions()` and defer division calculation to when it is needed.

  If we clear the divisions, we should also check that `additionalSubsets` and `additionalFields` are set correctly. Since the index is changed, `additionalSubsets` should be false, and `additionalFields` should be false for any subsets part of the input subsets.

- The user only gets access to one partition at a time, inhibiting any processing spanning across partitions (eg. global operations such as mean calculation). Enabling this kind of operation is a challenge for most data processing frameworks, not the focus of Fondant, and can be approximated by running on each partition instead.

  By implementing this as a `PandasTransformComponent` subclassing the `TransformComponent`, users can still use the `TransformComponent` to work with Dask directly.

### Implementation Steps/Tasks

- [ ] Implement `PandasTransformComponent`
- [ ] Update reusable and example components

### Testing

We can test this with unit tests.

### Documentation

We should document the `PandasTransformComponent` as the default way of building components with Fondant. Using the base `TransformComponent` directly should be explained as advanced usage.

**Comment by RobbeSneyders** [comment]
> Seems like we need to tackle #70 before implementing this feature

This isn't really a dependency as that issue is about the Fondant manifest index, while this is about the index of the pandas dataframe. It's trivial to check if 2 pandas Index objects are identical.

**Comment by GeorgesLorre** [comment]
Looks good. I'll like the approach of just doing this while being very aware of the limitations which we can tackle later.

What about the `LoadComponent` ?

**Comment by RobbeSneyders** [comment]
> I propose to check if the returned index is identical to the original index. If it is, this assumption is valid. If it is not, we call clear_divisions() and defer division calculation to when it is needed.
> 
> If we clear the divisions, we should also check that additionalSubsets and additionalFields are set correctly. Since the index is changed, additionalSubsets should be false, and additionalFields should be false for any subsets part of the input subsets.

This actually won't work, as we need to decide if we call `clear_divisions` at graph building time, while the index is only available at computation time. We need to switch this order, and look at the `additionalSubsets` and `additionalFields` to decide if the divisions should be cleared.

This raises the question which default we want for `additionalSubsets` and `additionalFields`. Currently this is `true`, which leads to a broken component if the index is changed and these fields are not set correctly. If we would change the default to `false`, not setting these fields will lead to a less performant but working component.

Not sure which is better. Being more robust or failing when performance is not optimized.
