### ISSUE TITLE
Improve data explorer UX

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#254]
Currently the user needs to provide the path to a manifest file in the data explorer, but this path is based on the mounted data directory, which makes this not straightforward.

It would be ideal if we can detect the different manifest files and provide a dropdown or folder structure instead which the user can use to select the manifest.

Ideally, we can do this for remote paths as well by letting the user eg. provide a remote base path which we scan for manifests.

**Comment by RobbeSneyders** [comment]
The data explorer throws an error when loading a subset without numeric columns. The `numeric_field` on the screenshot below is `None` in this case.

![Image](https://github.com/ml6team/fondant/assets/20990866/e430fdd4-5fd5-49aa-9afe-2fd71d09a8fd)

Traceback from terminal:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/main.py", line 48, in <module>
    build_numeric_analysis_plots(dataframe, numeric_fields)
  File "/app/widgets.py", line 180, in build_numeric_analysis_plots
    make_numeric_plot(dataframe, numeric_field, plot_type)
  File "/app/numeric_analysis.py", line 78, in make_numeric_plot
    data = dataframe[numeric_field].value_counts()
  File "/usr/local/lib/python3.8/site-packages/dask/dataframe/core.py", line 4851, in __getitem__
    raise NotImplementedError(key)
NotImplementedError: None

**Comment by PhilippeMoussalli** [comment]
Additional improvements: 

* Include more schema for text data
* Find a better way to infer images columns

**Comment by PhilippeMoussalli** [comment]
- [ ] Replace
