### ISSUE TITLE
Add internal argument to skip pipeline execution

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#315]

**Comment by satishjasthi** [comment]
@PhilippeMoussalli, Are you woking on this one or can I take this up?

**Comment by PhilippeMoussalli** [comment]
Hi @satishjasthi :) 

Thanks for contributing to Fondant! we're glad to have you in the team, 

Indeed this is something that I am planning to tackle as part of a larger [ticket](https://github.com/orgs/ml6team/projects/1/views/1?pane=issue&itemId=32410227). I think it's easier if I take this one up along with all the issues associated with it. 

I saw that you recently contributed to adding tests to the components themselves, would be great if you can continue on that ticket then we can look for other possible contributions that can be picked up

**Comment by satishjasthi** [comment]
Hey @PhilippeMoussalli  :)
Sure, that makes sense 👍
