### ISSUE TITLE
Create docs regarding setting up Kubeflow

### ISSUE THREAD

**Issue by NielsRogge** [ml6team/fondant#323]
When running Fondant pipelines on Kubeflow, one needs to follow this guide to make sure the Docker images can be read from the Github registry: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret.

We should docs on this, since it involves several steps.

**Comment by satishjasthi** [comment]
@GeorgesLorre @NielsRogge Can I take up this issue?

**Comment by RobbeSneyders** [comment]
This isn't really relevant for users when talking about reusable components, since they should be public. Pulling private images in general is something runner specific, so I would just refer to the documentation of the runner framework.
