### ISSUE TITLE
Remove Abstract test class and update tests

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#367]
In https://github.com/ml6team/fondant/pull/335 we decided to no longer use any abstraction for testing as it's straightforward to explicitly call the `transform` method of a component. We should remove the abstract test class and update the tests that use it.

@mrchtr agree?

**Comment by mrchtr** [comment]
Agreed. In practice, we discovered more limitations than advantages. In the future, it could be useful to offer commonly used methods needed for tests. However, for now, it is hard to estimate how these methods would look.
