### ISSUE TITLE
Further improve data explorer

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#396]
- Add component ID as entrypoint instead of manifest 
- Include more schema for text data 
- Find a better way to infer images columns

**Comment by RobbeSneyders** [comment]
Is this a duplicate of https://github.com/ml6team/fondant/issues/254?

**Comment by PhilippeMoussalli** [comment]
> Is this a duplicate of #254?

Yeah indeed, I'll close this one in favor of the other
