### ISSUE TITLE
Use types defined by kfp

### ISSUE THREAD

**Issue by GeorgesLorre** [ml6team/fondant#419]

**Comment by PhilippeMoussalli** [comment]
Linked to [this](https://github.com/ml6team/fondant/pull/411/files#r1317175144). 
On second thought, I am not sure if it's needed, to import it we would have to include kfp dependencies in the component spec. The current functionalities and types seem to provide everything that we need so I propose to close that ticket. @GeorgesLorre Wdyt?

**Comment by GeorgesLorre** [comment]
If there is no real benefit then indeed we can just close it
