### ISSUE TITLE
Handling default None values in compiled kubeflow pipelines

### ISSUE THREAD

**Issue by mrchtr** [ml6team/fondant#435]
If component arguments are of type `JsonObject` and the default value is set to `None`, we cannot
execute a Kubeflow pipeline.

For example, in the `pipeline.yaml` file:

```yaml
...
- client_kwargs
- None
```

This will result in the following error:

```
...
fondant: error: argument --client_kwargs: invalid loads value: 'None'
```

This issue is likely related to incorrect string parsing in the `executer:kubeflow2python_type`.

**Comment by RobbeSneyders** [comment]
Should be fixed by #524
