### ISSUE TITLE
Create a generic component that combines load from parquet and load from hub

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#475]

**Comment by PhilippeMoussalli** [comment]
Related to https://github.com/ml6team/fondant/pull/474#pullrequestreview-1648769479

**Comment by RobbeSneyders** [comment]
As discussed offline, I don't think we should merge these. The `LoadFromHub` component should be able to download datasets from HF hub in different formats. We can either have a separate `LoadFromParquet` component, or merge it with the `LoadFromFiles` component.

**Comment by PhilippeMoussalli** [comment]
ok closing this
