### ISSUE TITLE
controlnet-interior-design pipeline fails at laion_retrieval due to schema mismatch 

### ISSUE THREAD

**Issue by rehan21** [ml6team/fondant#503]
![image](https://github.com/ml6team/fondant/assets/28381280/fd5d1b51-bbc2-4554-81a9-c2289da9a63e)

Hello, 
I encountered this error, seems to be from dask : 

controlnet-pipeline-laion_retrieval-1   |     `ArrowTypeError('Expected a string or bytes dtype, got int64', 'Conversion failed for column id with type int64')`
controlnet-pipeline-laion_retrieval-1   |
controlnet-pipeline-laion_retrieval-1   | Expected partition schema:
controlnet-pipeline-laion_retrieval-1   |     url: string
controlnet-pipeline-laion_retrieval-1   |     id: string
controlnet-pipeline-laion_retrieval-1   |
controlnet-pipeline-laion_retrieval-1   | Received partition schema:
controlnet-pipeline-laion_retrieval-1   |     url: string
controlnet-pipeline-laion_retrieval-1   |     id: int64
controlnet-pipeline-laion_retrieval-1   |
controlnet-pipeline-laion_retrieval-1   | This error *may* be resolved by passing in schema information for
controlnet-pipeline-laion_retrieval-1   | the mismatched column(s) using the `schema` keyword in `to_parquet`.

I tried to fix it by modifying the to_parquet schema parameter, but there was no change.

Are you aware of this problem and is there a quick fix that can be used to continue the pipeline?

While reading through the existing issues, I noticed something was changed in https://github.com/ml6team/fondant/pull/436 below : 
![image](https://github.com/ml6team/fondant/assets/28381280/502ffec3-39c6-4494-ae5c-2212ad35134a)

Is it a side-effect of this update? If yes, I suppose I could just use an older version

**Comment by RobbeSneyders** [comment]
Hi @rehan21, this is due to the LAION index being mixed type. See https://github.com/ml6team/fondant/pull/485. You should be able to circumvent this by installing the latest version of Fondant from source:
```
pip install git+https://github.com/ml6team/fondant.git
```

**Comment by PhilippeMoussalli** [comment]
Hi @rehan21, this error should be resolved if you install the current latest version of fondant (0.6.1)

**Comment by rehan21** [comment]
Thank you,

I retried with the 0.6.1 version and received the below error with the example pipeline : 

"UnboundLocalError: local variable 'spec_ref' referenced before assignment"

I tried with different example components and received the same error

**Comment by PhilippeMoussalli** [comment]
could you give the full error stack?

**Comment by rehan21** [comment]
It is solved. I had installed the wrong version. 
I will close the issue as it is solved now.
Thanks for your help.
