### ISSUE TITLE
Add componentOp warning for unused set configurations

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#518]

**Comment by RobbeSneyders** [comment]
Can you explain what you mean with this @PhilippeMoussalli? Agree with taking any runner specific code out of the `ComponentOp` class, but I wouldn't want the user to have to change which `ComponentOp` class they use when submitting to a different runner.

**Comment by PhilippeMoussalli** [comment]
Perhaps we can return proper warnings if a certain field in the `componentOp` is set but will not be used in the specified runner (e.g. `node_pool_name` for local runner)
