### ISSUE TITLE
Generic filtering component

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#576]
Components that filter on a certain column value can be quite generic and easy to implement, there is no need to implement many filtering components. 

Perhaps we can create a generic filtering component where users define the columns to filter and the filtering conditions

**Comment by PhilippeMoussalli** [comment]
We can implement on generic DaskFilteringComponent

```python
class DaskFilteringComponent(BaseComponent):
    """Component thatfilters dataset based on a set of filter 
    DataFrame.
    """
    
def filter_task_df(df, filtering_conditions):
    """
    Translate generic filtering conditions to Dask filtering operations.
    """
    ops = {
        "==": operator.eq,
        "!=": operator.ne,
        ">": operator.gt,
        "<": operator.lt,
        ">=": operator.ge,
        "<=": operator.le,
    }

    for condition in filtering_conditions:
        column_name, op, value = condition
        if op in ops:
            op_func = ops[op]
            if isinstance(value, list):
                condition = None
                for v in value:
                    if condition is None:
                        condition = df[column_name].apply(op_func, args=(v,))
                    else:
                        condition |= df[column_name].apply(op_func, args=(v,))
                df = df[condition]
            else:
                df = df[df[column_name].apply(op_func, args=(value,))]

    return df

    def filter(self, dataframe: pd.DataFrame, filtering_conditions) -> pd.DataFrame:
        """
        Function that filters the component
        """
       return filter_task_df(dask_df, filtering_conditions)

```

**ComponentOp**

```python
filter_op = ComponentOp(
    component_dir="components/filter_op",
    arguments={
         filtering_conditions = [
                   ('A', '>', 2), 
                   ('B', '==', ['e','c'])
        ]
}
```

**Comment by RobbeSneyders** [comment]
Yes, something like this makes sense, although it might be limited. Eg. membership filtering (`isin()`) is missing.

It could be powerful if we let users submit custom functions to filter on as well. That should probably be possible with some kind of `eval`.

**Comment by PhilippeMoussalli** [comment]
I changed the structure a bit and managed to include all the native Dask filtering functions. 

Opened a [Draft PR](https://github.com/ml6team/fondant/pull/590) to make it easier to implement on the implementation. Would propose to continue the discussion there

**Comment by RobbeSneyders** [comment]
Not sure anymore about this component. I think it would be better to focus on Pyhon components so users can easily implement this kind of glue code themselves without having to build a complete custom component.

**Comment by RobbeSneyders** [comment]
Closing due to release of lightweight components.
