### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#604]
How to test a pipeline
How to run a GPU component
Subset/field clarification
How to scale
How to publish

**Comment by RobbeSneyders** [comment]
Yes, I already created #509 for that a while ago.

**Comment by PhilippeMoussalli** [comment]
Alright i'll close this ticket for now and remove the page.

**Comment by PhilippeMoussalli** [comment]
https://github.com/ml6team/fondant/compare/remove-faq?expand=1
