### ISSUE TITLE
Setup public ECR registry and pull reusable images from there

### ISSUE THREAD

**Issue by GeorgesLorre** [ml6team/fondant#618]

**Comment by GeorgesLorre** [comment]
Tried and doesn't seem te work. 



![Image](https://github.com/ml6team/fondant/assets/35808396/e975ad51-68a7-4472-abe6-a2bf1de6af08)


I (and others without access to the aws account) can pull the very same image locally so it is public and accessible 


```
docker pull public.ecr.aws/g7k8y4y9/load_from_hf_hub:main
````

**Comment by RobbeSneyders** [comment]
Could it be that you need to create a region specific url to pull the image on AWS? You might be able to use the `sagemaker.image_uris.retrieve` method.

**Comment by GeorgesLorre** [comment]
the `sagemaker.image_uris.retrieve` [method](https://sagemaker.readthedocs.io/en/stable/api/utility/image_uris.html) only seems to support a fixed [list](https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-us-east-1.html) of frameworks.

I tried using it with one of these frameworks to see what exactly it outputs:
```python
            image_uri = self.sagemaker.image_uris.retrieve(
                region="us-east-1",
                framework="Clarify"
            )
```

Gives `205585389593.dkr.ecr.us-east-1.amazonaws.com/download_images:latest`

**Comment by GeorgesLorre** [comment]
I just removed one of the private repo's that my pipeline (the same repo still exists in a public registry). I tried starting a pipeline with a URI similar to one you would get from `sagemaker.image_uris.retrieve`:

`281086077386.dkr.ecr.us-east-1.amazonaws.com/load_from_hf_hub:main`

But I get the following error:



![Image](https://github.com/ml6team/fondant/assets/35808396/e8736411-4259-4958-8b78-315184414b80)


so referring to a public image with the private uri syntax does not work
