### ISSUE TITLE
Enable better view of documents

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#631]
The text stored in Fondant datasets is in a string format, however, oftentimes we need to properly render it to a readable format by the user:   

  * Properly show basic formatting like newlines etc.
  * Show html documents
  * Show pdf documents
  * Show json 

We can do some basic detection on the text, by default this would be a raw text that can be rendered to a pdf. Otherwise, we can check if it's an html document or a json. The user can click on a dataset row or maybe even search by id to find the document. An example on how this can look like: 

https://github.com/ml6team/fondant/assets/47530815/25322292-57db-4262-bf01-ab39ec82a50d

We can either display the documents in the same tab or a separate tab. Other things to text would be the ability to properly reconstruct a pdf from a string. For that, we would probably have to develop a pdf/document loader component first to check the required representation needed when serializing the document.

**Comment by PhilippeMoussalli** [comment]
The raw text extracted from the llama index loaders. Advantages is that it's lightweight and does not require extra work. Though most formatting will be lost (document structure, colors, tables, ...)
We encode it as a base64 string in the loading document component and store that info in an extra column, this would enable us to render it back. The disadvantages here is that it's less lightweight as we're storing the data twice in different formats (llama doc + base64)

**Comment by RobbeSneyders** [comment]
Fixed in #666
