### ISSUE TITLE
Enable filtering, seaching and sorting through documents

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#632]

**Comment by PhilippeMoussalli** [comment]
Related to #641. We would need to have the ability to filter, search and sort through documents. 

** Filtering:** Available on [aggrid](https://discuss.streamlit.io/t/obtain-the-filters-in-streamlit-aggrid/24093/4). Has to be implemented manually on [streamlit dataframes](https://discuss.streamlit.io/t/how-to-filter-data-frame-via-a-column-and-have-a-check-box-column-to-filter-rows/48089/3)

**Search:** Available on both [aggrid](https://discuss.streamlit.io/t/obtain-the-filters-in-streamlit-aggrid/24093/4) and [streamlit dataframes](https://docs.streamlit.io/library/advanced-features/dataframes#:~:text=in%20the%20toolbar.-,Search,-%3A%20Click%20the%20search)

**Sort:** not sure if this is a crucial functionality. For [aggrid](https://docs.kanaries.net/topics/Streamlit/streamlit-aggrid#:~:text=Interactive%20Features%3A%20Streamlit%20AgGrid%20supports%20interactive%20features%20like%20sorting%2C%20filtering%2C%20and%20column%20resizing.) seems to be available. For [streamlit dataframes](https://docs.streamlit.io/library/advanced-features/dataframes#:~:text=When%20handling%20large%20datasets%20with%20more%20than%20150%2C000%20rows%2C%20Streamlit%20applies%20additional%20optimizations%20and%20disables%20column%20sorting.%20This%20can%20help%20to%20reduce%20the%20amount%20of%20data%20that%20needs%20to%20be%20processed%20at%20once%20and%20improve%20the%20app%27s%20performance.) only available for the first 150.000 first rows.

**Comment by RobbeSneyders** [comment]
Fixed in #691
