### ISSUE TITLE
Visualize an overview of the pipeline run

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#635]
We already have access to all the manifests use to create a pipeline, we can have the overview on a separate tab and build it with graphviz. 
![image](https://github.com/ml6team/fondant/assets/47530815/72f05f9a-a966-47e3-b7b8-111f9a885b96)

Graphviz constructs the plots using html script, perhaps we can expose it, render it and display it as an [iframe](https://docs.streamlit.io/library/components/components-api#:~:text=here%20first!-,Render%20an%20HTML%20string,-While%20st.text). We can insert hyperlinks on each field that enables to click on a field for a given component and directly visualize it. Maybe we can even select a few with a checkbox.

**Comment by PhilippeMoussalli** [comment]
It does not seem to be possible to save the graphviz rendered images to another format for customization since the rendering uses a custom . So we cannot provide the option to dynamically click on them to visualize them. This is not a big issue and was more of a nice to have since we can still select the columns with the field/component drop down menus. 

Streamlit does seem to have plugins to directly visualize the graphviz plots. 

https://docs.streamlit.io/library/api-reference/charts/st.graphviz_chart

**Comment by RobbeSneyders** [comment]
Fixed in #671
