### ISSUE TITLE
Local runner fails to bind port of dask dashboard

### ISSUE THREAD

**Issue by mrchtr** [ml6team/fondant#870]
Encountered a bug with:
- fondant `0.11dev1`
- Docker version 25.0.1, build 29cf629
- Docker Compose version v2.24.2

The Docker container cannot be started accordingly because during the start of a component, the port of the Dask dashboard is still allocated from the previous completed component.

E.g.
```
Error response from daemon: driver failed programming external connectivity on endpoint controlnet-pipeline-write_to_file-1 (cc30d244e30a23e8d565000b34c48bbc0e9444b8f706a3b4ecf22db073e7abfe): Bind for 0.0.0.0:8787 failed: port is already allocated
```

Temporary work around could be to disable the dask dashboard port binding, since it isn't used really at the moment.

**Comment by RobbeSneyders** [comment]
Did you run into this issue yourself? Can you check that your environment is clean and you don't have any detached services still active?

Also, we might not have to move the port completely, but just define it differently: https://github.com/docker/compose/issues/4950

**Comment by RobbeSneyders** [comment]
FYI, I can't reproduce this myself.
