### ISSUE TITLE
When building a custom component with fondant build, it requests to install docker

### ISSUE THREAD

**Issue by jBontinck** [ml6team/fondant#891]
I am starting from a clean setup with `pip install fondant` + I followed the instructions to install docker desktop.
I made an easy custom `DaskLoadComponent` and wanted to build it with `fondant build . -t v1`

I receive following message:
You need to install `docker` to use the `fondant build` command, you can install it with `pip install fondant[docker]`

I would expect that I don't need additional libraries given
- I installed fondant already (implicitly all requirements)
- I installed docker Desktop

I can solve this by following the feedback in the message, but is not what I expected

**Comment by jBontinck** [comment]
Coming back to this: 
When executing the command `pip install fondant[docker]` i get following message `zsh: no matches found: fondant[docker]`

**Comment by mrchtr** [comment]
@jBontinck thanks for the feedback. Looks like your shell is not interpreting the command correctly. For zsh `pip install "fondant[docker]"` should work. We should consider updating the log message here. 

For the case you want to install all extra requirements you could use `pip install "fondant[all]"`, but this will install a lot of things that you probably don't need right now. 

It looks like we should revisit the dependencies and extra groups.
