### ISSUE TITLE
Documentation - broken architecture link

### ISSUE THREAD

**Issue by KasperZutterman** [ml6team/fondant#932]
[architecture](https://fondant.ai/en/latest/docs/architecture.md) link is broken on the homepage. (Defined in README.md)

https://github.com/ml6team/fondant/blob/main/README.md?plain=1#L170

The link should point to `https://fondant.ai/en/latest/architecture/` instead of `https://fondant.ai/en/latest/docs/architecture.md`

**Comment by GeorgesLorre** [comment]
Fixed! Thx for letting us know
